# Standard systemd user session environment configuration for Wayland on Fedora
MOZ_ENABLE_WAYLAND=1
QT_QPA_PLATFORM="wayland;xcb"
ELECTRON_OZONE_PLATFORM_HINT=auto
GDK_BACKEND="wayland,x11"
_JAVA_AWT_WM_NONREPARENTING=1
